name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.10"]

    steps:
      - uses: actions/checkout@v3
        with:  # no need for the history
          fetch-depth: 1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get -y install cmake libgoogle-perftools-dev libunwind-dev
          python -m pip install --upgrade pip setuptools
          pip install "torch==2.2.2" "torchaudio==2.2.2" --index-url https://download.pytorch.org/whl/cpu
          pip install --no-cache-dir --editable=".[dev,tts]"

      - name: Test with pytest
        run: |
          pytest tests
